# Generated by Django 5.2.8 on 2025-11-12 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=30, unique=True, verbose_name='Código SKU')),
                ('nombre', models.CharField(max_length=120, verbose_name='Nombre del producto')),
                ('talla', models.CharField(blank=True, max_length=10, verbose_name='Talla')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Color')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('existencias', models.PositiveIntegerField(default=0, verbose_name='Existencias')),
            ],
        ),
    ]
