# Generated by Django 5.2.8 on 2025-11-15 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_remove_producto_color_remove_producto_existencias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tallas',
            field=models.CharField(blank=True, help_text='Escribe las tallas separadas por coma. Ejemplo: S,M,L,XL o 30,32,34', max_length=150),
        ),
    ]
