# Generated by Django 5.2.8 on 2025-11-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_pedido_pedidoitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=25, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='tallas',
            field=models.CharField(blank=True, help_text='Escribe tallas separadas por coma. Ejemplo: S,M,L,XL o 30,32,34', max_length=150),
        ),
    ]
